### ISSUE TITLE
create entry point for epmc xml tools

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-utils#108]
Create entry point for https://github.com/EBISPOT/gwas-utils/blob/master/epmcXMLTools/extract_epmc_tables.py so that we can execute it from a conda env.

**Comment by jdhayhurst** [comment]
non-issue entrypoint already exists: ```
$ extract-epmc-tables --help
usage: extract-epmc-tables [-h] [-pmid PMID]

optional arguments:
  -h, --help  show this help message and exit
  -pmid PMID  PMID```

**Comment by jdhayhurst** [comment]
Hi @eks-ebi, please could you let me know if a) this works and b) that the documentation here is sufficient to show you how to run this: https://www.ebi.ac.uk/seqdb/confluence/display/GOCI/Using+the+Codon+Cluster

**Comment by eks-ebi** [comment]
Hi @jdhayhurst, I accessed the cluster and then did `bsub -Is $SHELL` before trying to run the first-time Conda set-up... because you said to do that before doing _anything_... But the the Conda set-up then didn't work:

Error message: `cp: cannot stat '/homes/eks/.bashrc': No such file or directory`

Did I do the right thing? - want to check before trying this again without getting onto the compute node in case that's not ok

**Comment by eks-ebi** [comment]
@jdhayhurst  I got conda to work following the updated documentation, but only if I did the first-time set-up steps *before* `bsub -Is $SHELL` - hopefully that's ok, but if so I think it's still not quite clear from the instructions

**Comment by eks-ebi** [comment]
Other than that, the process works and I was able to run the extract-epmc-tables script fine!
