### ISSUE TITLE
Create a queuing mechanism for the pre-GWAS-SSF harmonisation

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-utils#151]
A queueing mechanism for the pre-gwas-ssf type that would also be more robust for gwas-ssf in case it doesn't run for a day.
```
HarmonisationType(enum):
	v1
	v0
	None

datamodel:
	study
	harmonisation_type
	index
	
1. python:
	1. get_files_for_harmonisation(number=x)
			pulls out first x number of files from db
			copies them to harmonisation dir
	2. add_files_for_harmonisation(list_of_studies, add_to_start=False, queue=HarmonisationType)
	3. get_harmonisation_type(study) -> HarmonisationType 
	4. refresh_to_harmonise_list()
		1. identify studies that have not been harmonised
--> nextflow runs
mongo backend?

**Comment by ljwh2** [comment]
From James: I released on Thursday and it has been running seamlessly every day, but I think it makes sense to switch it off for now. There seems to be a small  issue with the pre-gwas-ssf pipeline, that needs to be resolved (Yue is looking into it) and also with the gwas-ssf pipeline taking far too long and ultimately timing out. I’m happy to work with Yue as much as I can to try to resolve this so that both pipelines are up and working. We think the issues are probably environment related, i.e. docker image not properly updated or something along those lines.  I’ll update you with progress.
