### ISSUE TITLE
Curation App 'Reports' tab error

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/gwas-utils#42]
Clicking on 'Reports' tab, and then the sub-tab 'Overall weekly progress' (https://www.ebi.ac.uk/gwas/curation/reports/weekly_progress ) returns this error page:
![Screenshot 2020-10-05 at 09.06.33.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/d1af465a-ec46-4cb6-9e0d-0a49ccc49afe)

**Sub-issue:** (known issue but is usually only intermittent. At the moment seems permanent.)
Clicking on 'Reports' tab and then the sub-tab 'Open Targets Weekly progress' (https://www.ebi.ac.uk/gwas/curation/reports/reports_weekly_progress_targeted_arrays) returns this error page: 
![Screenshot 2020-10-05 at 10.06.55.png](https://images.zenhubusercontent.com/5e95cce7cc796e84ca614069/b8fc18af-6ba6-451e-b093-0dc1b8f14d04)

**Comment by tudorgroza** [comment]
@earlEBI @ljwh2 - I had a look into this and while the technical root of the issue is a query we're running against the DB - conceptually the reason requires a discussion w.r.t. how the resulting data is presented, to serve the main purpose of this report.

The table on that page displays, among other things, a comma-separated list of study IDs associated with a publication. The error you're encountering is caused by one (or multiple?) such publications having a VERY long list of studies - much larger than the limit supported by the DB. One example could be the 731 studies publication we worked on last week (Orru V). This begs the following questions: Even if the DB would cater for such a query (and we can indeed fix it by re-writing the query):
1. what would be the use of seeing (and scrolling through) a list of 731 study IDs?
2. do these stats have to be created on-demand? - since aggregating them (in the context of these new "norms" of hundreds of studies) will take ages.

Any feed-back would be greatly appreciated.

PS: The 500 error mentioned as a sub-issue is related to question #2 above.

/cc @sprintell

**Comment by tudorgroza** [comment]
Decision:
 * Fix weekly queries for normal and open targets
 * Implement the data aggregation as an async / scheduled task
 * List only the first 10 studies for each publication and leave the table as it is.
